### ISSUE TITLE
3.2.6 Project Plan

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#42]

**Comment by fabianchua6** [comment]
Update of Gantt Chart, project board and tasks to realign with new direction of project goals.

Notable changes:

- [x] No need for video
- [x] De-prioritise lab integration
- [x] Realign focus to be on module integration
- [x] Features should be developed by task owner on a full stack basis (i.e. frontend, backend, integration)
- [x] Factor in time for refactoring of code to conform to patterns taught in lecutre.
