### ISSUE TITLE
5.1 D2 Report | Start: 22/03/23 | End: 31/3/23

### ISSUE THREAD

**Issue by bran-donut** [JustBrandonLim/ICT2106_P2_Project_M1#81]
**Description**
The task involves conducting a comprehensive D2 project report for the Smart Home Manager application.

**Tasks**

- [x] Team's Features and Requirements
- [x] Team's Module Design
- [x] Detailed Design
- [x] Design Patterns
- [x] Construction Design
- [x] Screenshot of final interface
